### ISSUE TITLE
close to zero values in the A matrix

### ISSUE THREAD

**Issue by HegedusB** [CRG-CNAG/robustica#5]
Hi, I am currently trying to familiarize myself with the ICA. So I am not entirely clear what result I can expect from it. However, I noticed that the resulting A-matrix consists of zeros or numbers that are very close to zero. What could be the reason for this? I am analyzing an RNAseq dataset with 13617 rows and 214 columns. The log2CPM values were normalized by subtracting the mean of the controls from the other samples. Can you give me an explanation? Thank you in advance for your help!

**Comment by MiqG** [comment]
Can you provide the code snipped of the settings used to run `robustica`? 

Also, if possible could you share a histogram of the A matrix values? Note that ICA tries to minimize mutual information between its components such that they are as statistically independent as possible, hence it is expected that many weights in the ICA matrices are close to zero with some exceptions. See the original ICA publication: https://doi.org/10.1109/NNSP.2003.1318025

**Comment by HegedusB** [comment]
Hi, thanks for the quick reply. I use robustica as follows:
``
rica = RobustICA(n_components=214, robust_runs=100, tol=1e-7, whiten=True, max_iter=200)
``
I am inserting a histogram of the activity values here (all values are close to zero):
![image](https://github.com/CRG-CNAG/robustica/assets/9871809/acf47c94-4d95-4852-8a12-35882d59fbda)

I also tried the optICA package before, which gives higher A values during the iterative ICA steps, but unfortunately It can not finish the whole run.

**Comment by MiqG** [comment]
Great, two things:

- you should not use the same number of components as columns, always less. The rationale is that you want to summarize the genes into programs/regulons (S matrix) and then ask in which samples are those programs active (A matrix). My guess is that by using the same number of components as samples you have (214) the algorithm assigns 0 to everything except to one sample.

- my understanding is that what you plotted is a heatmap :). By histogram I meant something like this https://seaborn.pydata.org/generated/seaborn.histplot.html . Then it is easy to see whether everything is actually 0 or there are other values. Nevertheless, the color scale already indicates that you have numbers different than 0 (ranging -0.1  to 0.1), very few though because the heatmap looks all the same color to me.

I think running with say 100 components should change the picture because you'd be forcing the algorithm to make some combination of the samples

**Comment by HegedusB** [comment]
Hi, thank you for your really useful observations. It explains a lot.
If you don't mind, I would like to ask another question. Could filtering out genes from the X-table, whose expression is close to 0 in most samples, affect the ICA analysis in any way?
Thanks again!

**Comment by MiqG** [comment]
No problem @HegedusB !

I don't think filtering out genes close to 0 across all samples may affect ICA. But you could try running the algorithm either with all or those passing the filter and see how ICA matrix weights change. Note that the S matrix will lack those rows corresponding to the filtered-out genes.

I close the issue here but feel free to re-open it again. I am sure users will benefit from this discussion.
